ARG centos=8.3.2011
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        freeglut-devel \
        giflib-devel \
        java-devel \
        jpackage-utils \
        libjpeg-devel \
        libpng-devel \
        libtiff-devel \
        swig \
    && yum clean all && rm -rf /var/cache/yum
